import type { WeaponProfile } from "../engine/types";

/**
 * AP is stored as a positive number representing how much the save threshold
 * worsens (e.g. table value "AP-2" is stored here as ap: 2), matching the
 * engine's `armor = save + ap` convention.
 */
export const WEAPONS: Record<string, WeaponProfile> = {
  "Storm bolter (Crowe)": {
    name: "Storm bolter",
    isMelee: false,
    range: 24,
    attacks: 2,
    skill: 2,
    strength: 4,
    ap: 0,
    damage: 1,
    keywords: { rapidFire: 2 },
  },
  "Storm bolter": {
    name: "Storm bolter",
    isMelee: false,
    range: 24,
    attacks: 2,
    skill: 3,
    strength: 4,
    ap: 0,
    damage: 1,
    keywords: { rapidFire: 2 },
  },
  "Purifying Flame (Crowe)": {
    name: "Purifying Flame",
    isMelee: false,
    range: 18,
    attacks: 3,
    skill: 2,
    strength: 4,
    ap: 2,
    damage: 1,
    isPsychic: true,
    keywords: { antiKeyword: "INFANTRY", antiThreshold: 2, ignoresCover: true },
  },
  "Purifying Flame": {
    name: "Purifying Flame",
    isMelee: false,
    range: 18,
    attacks: 1,
    skill: 3,
    strength: 4,
    ap: 2,
    damage: 1,
    isPsychic: true,
    keywords: { antiKeyword: "INFANTRY", antiThreshold: 2, ignoresCover: true },
  },
  "Black Blade of Antwyr": {
    name: "Black Blade of Antwyr",
    isMelee: true,
    attacks: 5,
    skill: 2,
    strength: 6,
    ap: 2,
    damage: 2,
    keywords: { devastatingWounds: true, precision: true },
  },
  "Nemesis force weapon": {
    name: "Nemesis force weapon",
    isMelee: true,
    attacks: 3,
    skill: 3,
    strength: 6,
    ap: 2,
    damage: 2,
    isPsychic: true,
    keywords: {},
  },
  "Nemesis force weapon (Terminator)": {
    name: "Nemesis force weapon",
    isMelee: true,
    attacks: 4,
    skill: 3,
    strength: 6,
    ap: 2,
    damage: 2,
    isPsychic: true,
    keywords: {},
  },
  "Close combat weapon": {
    name: "Close combat weapon",
    isMelee: true,
    attacks: 3,
    skill: 3,
    strength: 4,
    ap: 0,
    damage: 1,
    keywords: {},
  },
  Psycannon: {
    name: "Psycannon",
    isMelee: false,
    range: 24,
    attacks: 3,
    skill: 3,
    strength: 8,
    ap: 1,
    damage: 2,
    isPsychic: true,
    keywords: {},
  },
  Psilencer: {
    name: "Psilencer",
    isMelee: false,
    range: 24,
    attacks: 6,
    skill: 3,
    strength: 5,
    ap: 0,
    damage: 1,
    isPsychic: true,
    keywords: { precision: true, sustainedHits: 1 },
  },
  Incinerator: {
    name: "Incinerator",
    isMelee: false,
    range: 12,
    attacks: { dice: "D6" },
    skill: 1, // unused — [TORRENT] auto-hits
    strength: 6,
    ap: 1,
    damage: 1,
    keywords: { ignoresCover: true, torrent: true },
  },
  "Fragstorm grenade launcher": {
    name: "Fragstorm grenade launcher",
    isMelee: false,
    range: 18,
    attacks: { dice: "D6" },
    skill: 3,
    strength: 4,
    ap: 0,
    damage: 1,
    keywords: { blast: true },
  },
  "Heavy psycannon": {
    name: "Heavy psycannon",
    isMelee: false,
    range: 24,
    attacks: 6,
    skill: 3,
    strength: 10,
    ap: 2,
    damage: 3,
    isPsychic: true,
    keywords: { ignoresCover: true },
  },
  Sublimator: {
    name: "Sublimator",
    isMelee: false,
    range: 18,
    attacks: 2,
    skill: 3,
    strength: 9,
    ap: 4,
    damage: { dice: "D6" },
    isPsychic: true,
    keywords: { melta: 4, twinLinked: true },
  },
  "Nemesis daemon greathammer": {
    name: "Nemesis daemon greathammer",
    isMelee: true,
    attacks: 5,
    skill: 3,
    strength: 14,
    ap: 3,
    damage: { dice: "D6", flat: 1 },
    isPsychic: true,
    keywords: {},
  },
};
